services:
  db:
    image: postgres:16.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_socket:/var/run/postgresql
    ports:
      - 5432:5432
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_lock_waits=on
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: "postgrest/postgrest:v12.0.3"
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@/${DB_NAME}?host=/var/run/postgresql
      PGRST_DB_SCHEMAS: "api, worker"
      PGRST_DB_ANON_ROLE: "anonymous"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_socket:/var/run/postgresql
  worker:
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    privileged: false
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKERS_PER_INSTANCE=${WORKERS_PER_INSTANCE}
    depends_on:
      db:
        condition: service_healthy

  db_bench:
    image: postgres:16.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./benchmark/db_socket:/var/run/postgresql
    ports:
      - 5432:5432
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_lock_waits=on
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: null
  db_socket: null
