---
  openapi: "3.0.0"
  info: 
    version: "1.0"
    title: "Avantation REST Template"
    description: "TODO: Add Description"
  servers: 
    - 
      url: "{scheme}://0.0.0.0:3000/{basePath}"
      variables: 
        scheme: 
          enum: 
            - "https"
            - "http"
          default: "http"
        basePath: 
          default: ""
  tags: 
    - 
      name: "task"
    - 
      name: "health"
  components: 
    schemas: 
      ErrorModel: 
        type: "object"
        properties: 
          code: 
            type: "string"
    securitySchemes: 
      JWT: 
        description: "You can create a JSON Web Token (JWT) during auth.\nUsage format: `Bearer <JWT>`\n"
        name: "Authorization"
        type: "apiKey"
        in: "header"
  paths: 
    /task/create: 
      post: 
        security: []
        tags: 
          - "task"
        summary: "task"
        parameters: []
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  task_type: 
                    type: "string"
                  start_after: 
                    type: "string"
              example: 
                task_type: "TypeA"
                start_after: "2022-10-07T20:04:17.916Z"
        responses: 
          202: 
            description: "Accepted"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    task_id: 
                      type: "string"
                    msg: 
                      type: "string"
                example: 
                  task_id: "2Foz7Zm9U2Pn0SYD1VbXvlYinyc"
                  msg: "Your task is queued"
          default: 
            description: "Unexpected error"
            content: 
              application/json: 
                example: 
                  message: "Sorry unable to perform operation."
    /health: 
      get: 
        security: []
        tags: 
          - "health"
        summary: "health"
        parameters: []
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    status: 
                      type: "string"
                example: 
                  status: "Healthy"
          default: 
            description: "Unexpected error"
            content: 
              application/json: 
                example: 
                  message: "Sorry unable to perform operation."
