[package]
name = "scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
queue.workspace = true

anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
