version: '3.7'

services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_cron,pg_stat_statements -c session_preload_libraries=auto_explain -c log_lock_waits=on
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scheduler:
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/scheduler.Dockerfile
    privileged: false
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  worker:
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    privileged: false
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WORKERS_PER_INSTANCE=${WORKERS_PER_INSTANCE}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: null
