[package]
name = "app-monolith"
version = "0.1.0"
edition = "2021"

[dependencies]
docs.workspace = true
http-server.workspace = true

anyhow.workspace = true
axum.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
