[package]
name = "worker"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
rand.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
